### PR TITLE
Fixes #41: add UIManager and NativeMethodsMixin

### LINKED ISSUE #41: why is setNativeProps not defined on react-web components?
the documentation says

> Component without setNativeProps method on web platform
```js
var setNativeProps = require('ReactSetNativeProps')
setNativeProps(this.refs.foo, {
  style: {
    top: 0
  }
})
```

and I can confirm that components like `View` don't have `setNativeProps` method. Is there a reason why it is not possible to have it? Why not having a web implementation of [NativeMethodsMixin.js](https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/NativeMethodsMixin.js) ?

This would avoid doing a lot of branching for handling this case.

### PR DESCRIPTION
**Pull request by gre**
fixes #41

now we can use `ref.setNativeProps()` as well as `ref.measure(cb)` and `measureLayout` on some native components like View and Text.

UIManager is also exposed (like in RN) and you can progressively add all the remaining methods as you need them.

### CODE REVIEW

**Comment by gre** [comment]
don't merge it yet. this raised some problem with Animated. because it will call setNativeProps. so we need to fix setNativeProps so it work the same as setting a style (it's not currently the case).

**Comment by gre** [comment]
but for now, i'll just disable Animated attempt to call setNativeProps

**Comment by gre** [comment]
(you can merge it now, I think it works correctly by disabling the Animated usage. need to consider #44 to  make animated more performant )

**Comment by yuanyan** [comment]
Big improve. <3

**Pull request merged**
